name = "ewdev/lute_std_lint"
version = "0.0.0"
description = "A Lute lint to check for allowed std references"
authors = ["EwDev (https://ewdev.net/)"]
repository = "https://github.com/ewd3v/lute_std_lint"
license = "MIT"

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
